### ISSUE TITLE
PIP packages versions are outdated in README file

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#12]
In section 1.4 of Module 1, pip packages lists outdated packages. The proper ones are as follows:

python-cinderclient (1.5.0)
python-glanceclient (1.2.0)
python-heatclient (0.8.0)
python-keystoneclient (2.0.0)
python-novaclient (2.35.0)
python-swiftclient (2.6.0)

**Comment by GuillaumeMorini** [comment]
Solved with commit a22700e
