### ISSUE TITLE
Bad formatting in Note

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#13]
In section 1.2.1 of Module 1, the note is badly formatted:

> Note: You should put the Metapod password in there and not $OS_PASSWORD in the environment variables Log out and log back in for your environment variables to become active.
Alternatively, run the command:

This makes it difficult to read and should be fixed.

**Comment by GuillaumeMorini** [comment]
Solved with commit  a2c705ea249ad28b9cf477ec0b29612b7ec88bb0
