### ISSUE TITLE
test_falvor should be renamed to test_flavor

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#14]
In section 1.4.3 of Module 1, running the "nova flavor-list" command brings a list of flavors, including the following:

> user15@22e58444ecde:~$ nova flavor-list
+--------------------------------------+-------------------------------------+-----------+------+-----------+------+-------+-------------+-----------+
| ID                                   | Name                                | Memory_MB | Disk | Ephemeral | Swap | VCPUs | RXTX_Factor | Is_Public |
+--------------------------------------+-------------------------------------+-----------+------+-----------+------+-------+-------------+-----------+
| 03621543-142a-42e7-b7bf-34b5b405e3ce | test_falvor                         | 512       | 10   | 0         |      | 1     | 1.0         | True      |

This flavor name should be renamed to "test_flavor"

**Comment by GuillaumeMorini** [comment]
Modified on Metacloud environment
