### ISSUE TITLE
Delete keypair should not be a step in the lab

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#17]
In section 1.4.5 of Module 1, the last step is to delete the keypair. This should not be shown as a "step" in the lab, since the keypair is needed in section 1.5.
The way to delete a keypair should be mentioned as a side note, and not be displayed like this

**Comment by GuillaumeMorini** [comment]
fixed with commit 11c02e4

**Comment by vesposito** [comment]
followind command? ;)
