### ISSUE TITLE
Formatting error in section 2.1.3 of Module 2

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#23]
In section 2.1.3 of Module 2, when running the git commit, the complete section is in a code wrapping div.

The first line should be, but then this one should be plain text:
"You may get an error if you are working with git for the first time, something like:"

Then this should also be plain text:
"Run"

The last 2 lines should also be plain text:
"to set your account's default identity.
Go ahead and run git config commands above and then continue onto below."

**Comment by GuillaumeMorini** [comment]
Solved with commit 2f8e353
