### ISSUE TITLE
Missing step before git clone in Module 2

### ISSUE THREAD

**Issue by vesposito** [Guismo1/DevNet-Express-3#26]
In section 2.1.6 of Module 2, before doing this command:
`git clone https://github.com/<your username>/DevNet-Express-3.git`

It would probably be cleaner to do first a:
`cd ~/`

Otherwise the git clone operation will happen inside the ~/cloudtest/ folder, which itself is a git repository cloned in section 2.1.3.

**Comment by GuillaumeMorini** [comment]
Closed with commit 745fdd9
